### ISSUE TITLE
Default User (only one user) not automatically selected

### ISSUE THREAD

**Issue by llelectronics** [maui-artwork/maui-artwork-sddm#1]
If only one user is there it should automatically select that user. 
Currently I have the problem that right after installation where I only create one user I only see the avatar picture and a login box. Apparently entering the password there alone will result in a wrong login as the user was not selected. (feels like some invisible one got selected) 
Clicking the one avatar then shows my username underneath it and I can then succesfuly enter my password. 
There is no such behavior in the default sddm theme so I think it is related to the theme itself.

**Comment by llelectronics** [comment]
Tried this today but it did not work: 

> diff --git a/maui-plasma/UserFrame.qml b/maui-plasma/UserFrame.qml
> index 5b0e2cb..855f152 100644
> --- a/maui-plasma/UserFrame.qml
> +++ b/maui-plasma/UserFrame.qml
> @@ -106,7 +106,7 @@ Item {
>              Keys.onReturnPressed: item.select()
> 
> ```
>      Component.onCompleted: {
> ```
> 
> \-                if (name === userModel.lastUser) {
> +                if (name === userModel.lastUser || userModel.count == 1) {
>                      item.select()
>                  }
>              }

I am currently out of ideas

**Comment by UriHerrera** [comment]
If there's only one user it does gets selected by default: https://drive.google.com/open?id=0B7tTOld4xNXCSy0xU3JxVUUwWmc

I'm using sddm version 0.13.0

_only until I entered my password I pressed any keys_

**Comment by llelectronics** [comment]
This works only if you logged in once in sddm before. Not directly after installation. At least not for me.

**Comment by star-buck** [comment]
Confirmed to not work directly after installation.

**Comment by UriHerrera** [comment]
I added background text to the password field so the user takes notice to click the avatar before entering the password.

If I understood correctly this is how it looks like, password field is showing but no username is displayed (notice the notice that I added):

![](http://i.imgur.com/BqTA1Nt.png)

And this _after_ the user has previously logged into sddm, password field and username are showing (which is what I recorded):

![](http://imgur.com/LWgywuu.png)

# 

I know it doesn't fully address the problem but it works as a workaround.

**Comment by star-buck** [comment]
Please try to fully fix this, this workaround is not acceptable in times
where we compete with so many other systems, thanks.

**Comment by UriHerrera** [comment]
@star-buck I'll try.

# 

@llelectronics as the theme assumes that there was a logged in user before and thus it shows the password field, perhaps we'd have change it to instead display the list users.

**Comment by UriHerrera** [comment]
@llelectronics @star-buck I've created a separate branch and uploaded a much, much simpler theme, please try it.

![](http://i.imgur.com/zeAuQjl.png)

This one _asks_ for both the username and password, a.k.a it lets the users type both things.

I created a new user "`test`"  in my VM; sddm defaults to my user `uri` but I can login with `test` by typing it. I don't know if that's close enough to a fresh install use case. I added the labels to make it clear which field is which.

This theme fixes the issue as [described](https://github.com/maui-artwork/maui-artwork-sddm/issues/1#issue-162888386).

**Comment by star-buck** [comment]
i asked David Edmundson to have a look at master branch, so lets wait for him and continue to work on something else the while

**Comment by davidedmundson** [comment]
Fixed: http://static.davidedmundson.co.uk/temp/

I've included a patch you an apply to the repo which expains what was wrong
and a zipfile of the whole thing if you just want to download that.

Note I've tried it on my machine recreating the bug with fake data, I've obviously not tried it in the full after installation case with this distribution.

**Comment by llelectronics** [comment]
@davidedmundson Thanks that works.
